name: Check Jirye Empty Room

on:
  push:
    branches:
      - master
  # schedule:
  #   - cron: '0 5 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test curl
        run: curl https://www.naver.com/

      - name: Test curl
        run: curl http://www.jirye.com/Book/booklist.php?

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
        env:
          CYPRESS_SLACK_WEBHOOK_URL: ${{ secrets.CYPRESS_SLACK_WEBHOOK_URL }}
