name: Check Jirye Empty Room

# on:
#   push:
#     branches:
#       - master
  # schedule:
  #   - cron: '0 5 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_SLACK_WEBHOOK_URL: ${{ secrets.CYPRESS_SLACK_WEBHOOK_URL }}
